version: '3'

networks:
  nestapi:

services:
  nest-api:
    build:
      context: .  # Specify the path to your app's directory
      dockerfile: Dockerfile  # Optional if your Dockerfile is named Dockerfile
    image: nest-api
    restart : unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - nestapi


